### ISSUE TITLE
Website's info is not refreshing after successful CI/CD

### ISSUE THREAD

**Issue by Liferenko** [ashfurrow/peerlab.community#101]
There was [commit](https://github.com/ashfurrow/peerlab.community/commit/0c1034aa2453e03a5003f6a1e4f2cf57a9aeb26d) quite awhile ago. But the data about peerlab location was not updated. 
Seems like something wrong with CD process

**Comment by ashfurrow** [comment]
Hmm you're right. [The last build](https://travis-ci.org/github/ashfurrow/peerlab.community/builds/767267506) failed to deploy:

```
git push origin gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/ashfurrow/peerlab.community.git/'
rake aborted!
```

I'll take a look later today 👍

**Comment by ashfurrow** [comment]
Fixed in https://github.com/ashfurrow/peerlab.community/commit/da5f8501a17e7ee62fee8003b2c6e72352ce2e31 . Thanks for letting me know!
