### ISSUE TITLE
Order events.yml

### ISSUE THREAD

**Issue by mbgg** [ashfurrow/peerlab.community#75]
The events.yml has grown over the time and everybody added his events at the end.
That gives as a good historical view of the events added, but makes it more difficult to find events for your city.

So why not order the events? My proposal would be to use alphabetic order of the city name, but other options would be possible (e.g. name of the country).

I could give it a try but wanted to know what the others think about it.

**Comment by ashfurrow** [comment]
Sounds great 👍 I think we should follow that up with CI tooling (probably [Danger](https://danger.systems/ruby/) to fail PRs if they're not sorted.

**Comment by ashfurrow** [comment]
(I can take care of the Danger part.)
